name: wokwi
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
jobs:
  wokwi:
    env:
        OPENLANE_TAG:   2022.02.23_02.50.41
        OPENLANE_IMAGE_NAME:    efabless/openlane:$(OPENLANE_TAG)
        OPENLANE_ROOT:  /home/runner/openlane
        PDK_ROOT:       /home/runner/pdk
        PDK:            sky130A

    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v2

    # need python
#    - name: setup python
#      uses: actions/setup-python@v2
#      with:
#        python-version: '3.7.7' # install the python version needed

    # build pdk
    - name: pdk & caravel
      run: |
        cd $HOME
        git clone https://github.com/efabless/caravel_user_project.git -b mpw-6c
        cd caravel_user_project
        make setup

    - name: fetch Verilog
      run: make fetch

    - name: make GDS
      run: make harden

    - name: show files
      run: find runs/wokwi/results

    # archive the gds and final report for the user project wrapper
    - name: Archive GDS
      uses: actions/upload-artifact@v2
      with:
          # path depends on the tag and the module name
          name: GDS
          path: runs/wokwi/results/final/gds/user_module.gds

